### PR TITLE
Enable External Clock sources on the Xync

### PR DESCRIPTION
**Pull request by sjkelly**
These are the changes required to enable external clock sources on the XTRX. Particularly the 19.2MHz clock sourced from the Xync carrier. There are some differences in (gain?) response and possibly noise.

External Clock (19.2 MHz):
image

Internal Clock (26 MHz):

image

### CODE REVIEW

**Comment by sjkelly** [comment]
For reference, to change the clock source:
```
    Device(first(Devices(;device_kwargs...))) do dev
        # Get some useful parameters
        format = dev.rx[1].native_stream_format
        fullscale = dev.tx[1].fullscale

        dev.clock_source = "external"
        ...
        ```

**Review by staticfloat — APPROVED** [review]

**Comment by staticfloat** [comment]
Why is SoapySDR bumped here?

**Comment by sjkelly** [comment]
We need the clock source support.

**Comment by staticfloat** [comment]
I see; merge when ready then!

**Pull request merged**
